apiVersion: v1
kind: Pod

metadata:
  name:myapp-pod

spec:
  containers:
   -name: webserver
    image: nginx
   affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
           - matchExpressions:
               - key: size
                 operator: Exists
